
local globals = {
	MASTER_VOLUME = 0.75,
	MUSIC_VOLUME = 0.4,
	DEFAULT_MUSIC_DURATION = 174.69,
	CROSSFADE_TIME = 0,
	
	PHYSICS_SCALE = 300,
	LINE_SPACING = 36,
	INC_OFFSET = -15,
	
	WORLD_WIDTH = 32,
	WORLD_HEIGHT = 20,
	SHOP_WIDTH = 500,
	GRID_SIZE = 96,
	CORNER_SPEED_MULT = 1.15,
	TRAIN_SPAWN_TIME = 10,
	SHOP_SLOTS = 3,
	DECK_SIZE_MULT = 3,
	TRACK_CREDIT_TIME = 10,
}

return globals