
local globals = {
	MASTER_VOLUME = 0.75,
	MUSIC_VOLUME = 0.4,
	DEFAULT_MUSIC_DURATION = 174.69,
	CROSSFADE_TIME = 0,
	
	PHYSICS_SCALE = 300,
	LINE_SPACING = 36,
	INC_OFFSET = -15,
	
	BLACK_BAR_LEEWAY = 50,
	WORLD_WIDTH = 26,
	WORLD_HEIGHT = 15,
	SHOP_WIDTH = 500,
	RESOURCE_BONUS_HEIGHT = 120,
	GRID_SIZE = 96,
	CORNER_SPEED_MULT = 1.15,
	TRAIN_SPAWN_TIME = 10,
	SHOP_SLOTS = 4,
	SHOP_BIN_SLOTS = 2,
	DECK_SIZE_MULT = 3,
	TRACK_CREDIT_TIME = 10,
	
	STARTING_TRACK = 12,
	TRAVEL_SCORE = 5,
	
	BASE_DELIVER_SCORE = 100,
	PRIORITY_DELIVER_SCORE = 300,
	DELIVERY_PER_TRACK = 10,
	GAME_TIME = 10 * 60,
	
	BONUS_REQ = 10,
	BONUS_REQ_INC = 5,
	
	ORDER_SIZE = 5,
	ORDER_SIZE_INC = 5,
}

return globals