
local mapData = {
	dimensions = {
		width = 26,
		height = 15,
		tileSize = 96,
	},
	track = {
		{pos = {0 + 5, 0 + 7}, rot = 0, trackType = "factory"},
		{pos = {1 + 5, 0 + 7}, rot = 0, trackType = "straight"},
		{pos = {2 + 5, 0 + 7}, rot = 2, trackType = "split"},
		{pos = {2 + 5, 1 + 7}, rot = 1, trackType = "straight"},
		{pos = {2 + 5, 2 + 7}, rot = 0, trackType = "split"},
		{pos = {3 + 5, 2 + 7}, rot = 0, trackType = "straight"},
		{pos = {4 + 5, 2 + 7}, rot = 0, trackType = "straight"},
		{pos = {4 + 5, 2 + 7}, rot = 1, trackType = "branch_left"},
		{pos = {4 + 5, 3 + 7}, rot = 3, trackType = "curve"},
		{pos = {5 + 5, 3 + 7}, rot = 2, trackType = "split"},
		{pos = {5 + 5, 2 + 7}, rot = 1, trackType = "straight"},
		{pos = {5 + 5, 1 + 7}, rot = 1, trackType = "straight"},
		{pos = {5 + 5, 0 + 7}, rot = 1, trackType = "curve"},
		{pos = {4 + 5, 0 + 7}, rot = 0, trackType = "curve"},
		{pos = {4 + 5, 1 + 7}, rot = 1, trackType = "straight"},
		{pos = {2 + 5, -1 + 7},rot = 0, trackType =  "curve"},
		{pos = {3 + 5, -1 + 7},rot = 0, trackType =  "straight"},
		{pos = {4 + 5, -1 + 7},rot = 0, trackType =  "sawmill"},
		{pos = {5 + 5, -1 + 7},rot = 0, trackType =  "straight"},
		{pos = {6 + 5, -1 + 7},rot = 0, trackType =  "town"},
		{pos = {7 + 5, -1 + 7},rot = 0, trackType =  "straight"},
		{pos = {8 + 5, -1 + 7},rot = 0, trackType =  "farm"},
		{pos = {9 + 5, -1 + 7},rot = 0, trackType =  "straight"},
		{pos = {10+ 5, -1 + 7},rot = 0, trackType =  "mine"},
		{pos = {11+ 5, -1 + 7},rot = 0, trackType =  "straight"},
		{pos = {5 + 5, 4 + 7}, rot = 1, trackType = "signal"},
		{pos = {5 + 5, 5 + 7}, rot = 1, trackType = "cross"},
		{pos = {5 + 5, 6 + 7}, rot = 3, trackType = "curve"},
		{pos = {6 + 5, 6 + 7}, rot = 2, trackType = "curve"},
		{pos = {6 + 5, 5 + 7}, rot = 1, trackType = "curve"},
		{pos = {4 + 5, 5 + 7}, rot = 0, trackType = "town", setData = {}},
		{pos = {3 + 5, 5 + 7}, rot = 0, trackType = "straight"},
		{pos = {2 + 5, 5 + 7}, rot = 3, trackType = "curve"},
		{pos = {2 + 5, 4 + 7}, rot = 1, trackType = "straight"},
		{pos = {2 + 5, 3 + 7}, rot = 1, trackType = "straight"},
		
		{pos = {10+ 5, -1 + 6}, rot = 0, trackType = "mountain_small"},
		{pos = {4 + 5, -1 + 6}, rot = 0, trackType = "forest"},
		{pos = {4 + 4, -1 + 6}, rot = 0, trackType = "forest"},
		{pos = {4 + 5, -1 + 5}, rot = 0, trackType = "forest"},
		{pos = {4 + 4, -1 + 5}, rot = 0, trackType = "forest"},
		{pos = {4 + 3, -1 + 5}, rot = 0, trackType = "forest"},
		
		{pos = {8 + 5, -1 + 6}, rot = 0, trackType = "field"},
		{pos = {9 + 5, -1 + 6}, rot = 0, trackType = "field"},
		{pos = {8 + 5, -1 + 5}, rot = 0, trackType = "field"},
		{pos = {9 + 5, -1 + 5}, rot = 0, trackType = "field"},
	}
}

return mapData
